"""fix

Revision ID: 5ebc71c8f80f
Revises: 490ee897529c
Create Date: 2026-02-07 13:10:29.975068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ebc71c8f80f'
down_revision: Union[str, Sequence[str], None] = '490ee897529c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('users', 'public_message_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'was_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('was_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'public_message_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
